version: "3"
services:
  mysql:
    image: mysql:5.7.16
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      TZ: Asia/Shanghai
  sql2slack:
    build: ./
    image: dalongrong/sql2slack
    command: -jobs-dir /opt/hcls
    volumes:
      - "./hcls:/opt/hcls"
